[env:nano]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200

; Use the src folder in this subproject

; This subproject compiles the canonical sketch located at ../nano/relay_nano.ino
; A small wrapper file in src/ will include the canonical sketch so PlatformIO can build it.

